mysql: &mysql
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8mb4
  collation: utf8mb4_bin
  timeout: 5000

development:
  <<: *mysql
  database: db/ems_development

test:
  <<: *mysql
  database: db/ems_test

production:
  <<: *mysql
  database: db/ems_production
